### ISSUE TITLE
New fields available (including Critical issue count)

### ISSUE THREAD

**Issue by sburf-rokt** [picatz/snyk#5]
The picatz/snyk library is not reporting critical severity vulnerability counts.

The Projects structure provided by the underlying Snyk API now includes a critical severity issue count, along with new fields describing the image or artifact that was scanned and what branch it relates to:
https://snyk.docs.apiary.io/#reference/projects/all-projects/list-all-projects

While reviewing structures, Organization now has slug and URL fields:
https://snyk.docs.apiary.io/#reference/organizations/the-snyk-organization-for-a-request/list-all-the-organizations-a-user-belongs-to

I have prepared a pull request that adds these fields:
https://github.com/picatz/snyk/pull/4
The PR also makes Organization a type.  Previously Organizations []struct made it difficult to use a single organization in relying code.

**Comment by picatz** [comment]
👋 Hello @sburf-rokt! Thank you for the PR, happy to review it.

**Comment by picatz** [comment]
Reviewed and merged the PR, closing the issue. Thanks again!
